-- 16
SELECT COUNT(INV_NUMBER) AS QTD_FATURAS 
FROM INVOICE;

-- 17
SELECT COUNT(CUS_CODE) AS QTD_CLIENTES
FROM CUSTOMER
WHERE CUS_BALANCE > 500;

-- 18
SELECT C.CUS_CODE, I.INV_NUMBER, I.INV_DATE, P.P_DESCRIPT, L.LINE_UNITS, L.LINE_PRICE
FROM CUSTOMER C
INNER JOIN INVOICE I ON C.CUS_CODE = I.CUS_CODE
INNER JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
INNER JOIN PRODUCT P ON L.P_CODE = P.P_CODE
ORDER BY C.CUS_CODE, I.INV_NUMBER;

-- 19
SELECT C.CUS_CODE, I.INV_NUMBER, P.P_DESCRIPT, L.LINE_UNITS AS [Units Bought], L.LINE_PRICE AS [Unit Price], (L.LINE_UNITS * L.LINE_PRICE) AS Subtotal
FROM CUSTOMER C
INNER JOIN INVOICE I ON C.CUS_CODE = I.CUS_CODE
INNER JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
INNER JOIN PRODUCT P ON L.P_CODE = P.P_CODE
ORDER BY C.CUS_CODE, I.INV_NUMBER, P.P_DESCRIPT;

-- 20
SELECT C.CUS_CODE, C.CUS_BALANCE, SUM(L.LINE_UNITS * L.LINE_PRICE) AS [Total Purchases]
FROM CUSTOMER C
INNER JOIN INVOICE I ON C.CUS_CODE = I.CUS_CODE
INNER JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
GROUP BY C.CUS_CODE, C.CUS_BALANCE
ORDER BY C.CUS_CODE;

-- 21
SELECT C.CUS_CODE, C.CUS_BALANCE, SUM(L.LINE_UNITS * L.LINE_PRICE) AS [Total Purchases], COUNT(L.INV_NUMBER) AS [Number of Purchases]
FROM CUSTOMER C
INNER JOIN INVOICE I ON C.CUS_CODE = I.CUS_CODE
INNER JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
GROUP BY C.CUS_CODE, C.CUS_BALANCE
ORDER BY C.CUS_CODE;

-- 22
SELECT 
    C.CUS_CODE, 
    C.CUS_BALANCE, 
    SUM(L.LINE_UNITS * L.LINE_PRICE) AS [Total Purchases],
    COUNT(L.INV_NUMBER) AS [Number of Purchases],
    AVG(L.LINE_UNITS * L.LINE_PRICE) AS [Average Purchase Amount]
FROM CUSTOMER C
INNER JOIN INVOICE I ON C.CUS_CODE = I.CUS_CODE
INNER JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
GROUP BY C.CUS_CODE, C.CUS_BALANCE
ORDER BY C.CUS_CODE;

-- 23
SELECT 
    INV_NUMBER, 
    SUM(LINE_UNITS * LINE_PRICE) AS [Invoice Total]
FROM LINE
GROUP BY INV_NUMBER
ORDER BY INV_NUMBER;

-- 24
SELECT 
    I.CUS_CODE, 
    I.INV_NUMBER, 
    SUM(L.LINE_UNITS * L.LINE_PRICE) AS [Invoice Total]
FROM INVOICE I
INNER JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
GROUP BY I.CUS_CODE, I.INV_NUMBER
ORDER BY I.CUS_CODE, I.INV_NUMBER;

-- 25
SELECT
    I.CUS_CODE, 
    COUNT(DISTINCT I.INV_NUMBER) AS [Number of Invoices], 
    SUM(L.LINE_UNITS * L.LINE_PRICE) AS [Total Customer Purchases]
FROM INVOICE I
INNER JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
GROUP BY I.CUS_CODE
ORDER BY I.CUS_CODE;

-- 26
SELECT 
    COUNT(INV_NUMBER) AS [Total Invoices],
    SUM(Invoice_Total) AS [Total Sales],
    MIN(Invoice_Total) AS [Minimum Sale],
    MAX(Invoice_Total) AS [Largest Sale],
    AVG(Invoice_Total) AS [Average Sale]
FROM (
    SELECT INV_NUMBER, SUM(LINE_UNITS * LINE_PRICE) AS Invoice_Total
    FROM LINE
    GROUP BY INV_NUMBER
) AS Subconsulta;

-- 27
SELECT DISTINCT 
    C.CUS_CODE, 
    C.CUS_BALANCE
FROM CUSTOMER C
INNER JOIN INVOICE I ON C.CUS_CODE = I.CUS_CODE
ORDER BY C.CUS_CODE;

-- 28
SELECT MIN(CUS_BALANCE) AS [Minimum Balance], 
       MAX(CUS_BALANCE) AS [Maximum Balance], 
       AVG(CUS_BALANCE) AS [Average Balance]
FROM CUSTOMER
WHERE CUS_CODE IN (SELECT DISTINCT CUS_CODE FROM INVOICE);

-- 29
SELECT SUM(CUS_BALANCE) AS [Total Balances],
       MIN(CUS_BALANCE) AS [Minimum Balance], 
       MAX(CUS_BALANCE) AS [Maximum Balance], 
       AVG(CUS_BALANCE) AS [Average Balance]
FROM CUSTOMER;

-- 30
SELECT CUS_CODE, CUS_BALANCE
FROM CUSTOMER
WHERE CUS_CODE NOT IN (SELECT DISTINCT CUS_CODE FROM INVOICE);

-- 31
SELECT SUM(CUS_BALANCE) AS [Total Balance],
       MIN(CUS_BALANCE) AS [Minimum Balance], 
       MAX(CUS_BALANCE) AS [Maximum Balance], 
       AVG(CUS_BALANCE) AS [Average Balance]
FROM CUSTOMER
WHERE CUS_CODE NOT IN (SELECT DISTINCT CUS_CODE FROM INVOICE);

-- 32
SELECT P_DESCRIPT, P_QOH, P_PRICE, (P_QOH * P_PRICE) AS Subtotal
FROM PRODUCT
ORDER BY Subtotal DESC;

-- 33
SELECT SUM(P_QOH * P_PRICE) AS [Total Value of Inventory]
FROM PRODUCT;