CREATE TABLE VENDOR (
    V_CODE INT PRIMARY KEY,
    V_NAME VARCHAR(35) NOT NULL,
    V_CONTACT VARCHAR(15),
    V_AREACODE CHAR(3),
    V_PHONE VARCHAR(8),
    V_STATE CHAR(2),
    V_ORDER CHAR(1)
);

CREATE TABLE CUSTOMER (
    CUS_CODE INT PRIMARY KEY,
    CUS_LNAME VARCHAR(15) NOT NULL,
    CUS_FNAME VARCHAR(15) NOT NULL,
    CUS_INITIAL CHAR(1),
    CUS_AREACODE CHAR(3),
    CUS_PHONE VARCHAR(8),
    CUS_BALANCE DECIMAL(9,2) DEFAULT 0.00
);

CREATE TABLE PRODUCT (
    P_CODE VARCHAR(10) PRIMARY KEY,
    P_DESCRIPT VARCHAR(35) NOT NULL,
    P_INDATE DATE,
    P_QOH INT NOT NULL,
    P_MIN INT,
    P_PRICE DECIMAL(8,2) NOT NULL,
    P_DISCOUNT DECIMAL(4,2),
    V_CODE INT,
    FOREIGN KEY (V_CODE) REFERENCES VENDOR(V_CODE)
);

CREATE TABLE INVOICE (
    INV_NUMBER INT PRIMARY KEY,
    CUS_CODE INT,
    INV_DATE DATE NOT NULL,
    FOREIGN KEY (CUS_CODE) REFERENCES CUSTOMER(CUS_CODE)
);

CREATE TABLE LINE (
    INV_NUMBER INT,
    LINE_NUMBER INT,
    P_CODE VARCHAR(10),
    LINE_UNITS INT NOT NULL,
    LINE_PRICE DECIMAL(8,2) NOT NULL,
    PRIMARY KEY (INV_NUMBER, LINE_NUMBER),
    FOREIGN KEY (INV_NUMBER) REFERENCES INVOICE(INV_NUMBER),
    FOREIGN KEY (P_CODE) REFERENCES PRODUCT(P_CODE)
);